services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
      - credentials
    networks:
      - inception
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_USER_FILE: /run/secrets/credentials
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p$(cat /run/secrets/db_root_password) | grep -q alive"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_HOST: ${WP_DB_HOST}
      WP_DB_USER_FILE: /run/secrets/credentials
      WP_DB_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "php-fpm81 -t || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html:ro
      # - static_data:/usr/share/nginx/static:ro
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:443"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    env_file:
      - .env
    networks:
      - inception
      - bonus
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
  static:
    container_name: static
    build: ./requirements/bonus/static
    networks:
      - inception
      - bonus
    ports:
      - "8081:80"
    restart: unless-stopped

  # redis:
  #   container_name: redis
  #   build: ./requirements/bonus/redis
  #   env_file:
  #     - .env
  #   networks:
  #     - inception
  #     - bonus
  #   volumes:
  #     - redis_data:/data
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # ftp:
  #   container_name: ftp
  #   build: ./requirements/bonus/ftp
  #   env_file:
  #     - .env
  #   networks:
  #     - inception
  #     - bonus
  #   volumes:
  #     - wordpress_data:/var/www/html
  #     - ftp_data:/home/ftpuser
  #   ports:
  #     - "21:21"
  #     - "30000-30010:30000-30010"
  #   restart: always
  #   depends_on:
  #     - wordpress

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  credentials:
    file: ./secrets/credentials.txt

networks:
  inception:
  bonus:

volumes:
  mariadb_data:
  wordpress_data:
  redis_data:
  static_data:
  ftp_data: